# ???? property?? ??? yml??? ???? ????.
# ? ? ???? ??? ? ? ???? ?? ???

spring:
  h2:
    console:
      enabled: true # http://localhost:8080/h2-console ? ???? ?? ??
  jpa:
    defer-datasource-initialization: true # Spring Boot 2.5 ????? data.sql ? Hibernate ? ????? ?? ???? Hibernate ???? ?? ??? ???? ???? ???? ?? data.sql ? ????? ?? ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create-drop # ddl-auto? ???? generate-ddl ??? ????.
    generate-ddl: true # ???? ???? ???? ddl? ??, ????? false??? ???? ??? true? ????.

  datasource:
    url: jdbc:mysql://book-manager.c0xe9k5nhnaa.ap-northeast-2.rds.amazonaws.com:3306/book_manager
    username: admin
    password: wlgud1025017
    initialization-mode: always  # ddl-auto?? ??
server:
  port: 8080