# ???? property?? ??? yml??? ???? ????.
# ? ? ???? ??? ? ? ???? ?? ???

spring:
  h2:
    console:
      enabled: true # http://localhost:8080/h2-console ? ???? ?? ??
  jpa:
    defer-datasource-initialization: true # Spring Boot 2.5 ????? data.sql ? Hibernate ? ????? ?? ???? Hibernate ???? ?? ??? ???? ???? ???? ?? data.sql ? ????? ?? ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080